# .github/workflows/publish-npm.yaml
# This workflow is triggered when a new GitHub Release is published.
# Its purpose is to publish the package to the NPM registry.

name: Publish to NPM

on:
  release:
    # We use 'published' instead of 'created' as it ensures the release is fully public.
    types: [published]

jobs:
  publish:
    name: Publish to NPM Registry
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # Required for 'provenance' flag on npm publish

    steps:
      - name: Checkout repository
        # This action checks out the specific commit associated with the release tag.
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 'lts/*'
          cache: 'npm'
          # Point to the official NPM registry
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        # 'npm ci' is recommended for CI environments for faster, more reliable installs.
        run: npm ci

      - name: Verify tests pass on release code
        run: npm test

      - name: Publish to NPM
        # The NODE_AUTH_TOKEN is used by the 'npm publish' command for authentication.
        # --provenance flag generates a non-forgeable attestation about where and how the package was built.
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
